name: test-plutoprint-py310-bullseye
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    container: python:3.10-slim-bullseye
    steps:
      - name: Install plutoprint
        run: pip install -v --no-cache-dir plutoprint

      - name: Run plutoprint
        run: |
          python -m plutoprint --info
          python -m plutoprint https://en.wikipedia.org/wiki/Bjarne_Stroustrup hello.pdf

      - name: Upload hello.pdf
        uses: actions/upload-artifact@v4
        with:
          name: hello-pdf
          path: hello.pdf
          if-no-files-found: error
