name: test-html2pdf-bullseye

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    container: debian:bullseye-slim
    steps:
      - name: Install and test plutoprint
        run: |
          apt-get update && apt-get install -y --no-install-recommends python3-pip
          pip3 install plutoprint
          python3 -m plutoprint --info
          
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract and run
        run: |
          tar -xzf plutobook-linux-x64.tar.gz
          chmod +x plutobook-linux-x64/tools/html2pdf
          ./plutobook-linux-x64/tools/html2pdf --info
